### ISSUE TITLE
Sample data must avoid valid looking data

### ISSUE THREAD

**Issue by ericjohnson-tibco** [TIBCOSoftware/TCSTK-Angular#50]
For example, in this file:
TCSTK-Angular/projects/tibco-tcstk/tc-events-lib/src/lib/models/tc-events.ts

It looks like the file contains what was once a valid API token. (Also includes references to tibco.com that do not point to a valid site.)

In sample data, please always use obviously bogus sample data. Instead of tibco.com, use example.com. Instead of @outlook.com, use @example.com.

Otherwise, automated checks highlight the code, and we need to spend time dealing with it.

**Comment by JGrotex** [comment]
Hi Eric,

thanks for highlighting this one!
Who gets informed by this 'automated checks'? Can we get added to this
Lists for our Repo's?

I removed 'outlook.com' from the Comment Section.
As this is a sample response of a Service where the Datatype always starts
with 'www.tibco.com/be/>' it would be very wrong to change that to 'example
.com', so I need to leave that as it is coming from TIBCO Business Events.

On the other hand, I can understand that the automated check highlights the
code if it is in a property file or part of the executable source.
but here it is all in a comment section, and get never executed.

regards, Jörg

*Jörg Grote **- *Office of the CTO - Principal Solutions Architect | *M*  +49
171 5664 015 | *E* jgrote@tibco.com | *W* www.tibco.com | *TIBCO Software*
|  3307 Hillview Avenue, Palo Alto, CA 94304
<https://maps.google.com/?q=3307+Hillview+Avenue,+Palo+Alto,+CA+94304&entry=gmail&source=g>

<https://github.com/jgrotex>      <https://www.linkedin.com/in/jgrote/>
<https://twitter.com/JoergGODev>

<https://now.tibco.com/>

The information transmitted in this electronic communication is intended
only for the person or entity to whom it is addressed and may contain
confidential and/or privileged material. Any review, retransmission,
dissemination or other use of or taking of any action in reliance upon this
information by persons or entities other than the intended recipient is
prohibited.




Am Di., 7. Apr. 2020 um 01:12 Uhr schrieb Eric Johnson <
notifications@github.com>:
